GLOBAL_TOKENS = r'/media/zivlit/Seagate Expansion Drive/Projects/global_tokens.txt'
TOKEN_FREQUENCIES = r'/media/zivlit/Seagate Expansion Drive/Projects/token_freqs.json'
TOKEN_VECTORS = r'/media/zivlit/Seagate Expansion Drive/Projects/token_vectors.json'
INDICATIVITY_SCORES = r'/media/zivlit/Seagate Expansion Drive/Projects/token_indicativity_scores.json'
FILTERED_POSTS = r'/media/zivlit/Seagate Expansion Drive/Projects/filtered_posts.json'
